[build]
  command = "cd e-commerce && npm install && npm run build"
  publish = "e-commerce/dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 